version: '2.0'
services:
    nginx:
        image: nginx:1.13.6-alpine
        hostname: nginx
        privileged: true
        restart: always
        ports:
            - 80:80/tcp
        networks:
            wordpress:
                aliases:
                    - nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./volumedata/www:/var/www/html:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    wordpress:
        image: wordpress:4.9.1-php7.1-fpm-alpine
        hostname: php
        privileged: true
        restart: always
        networks:
            wordpress:
                aliases:
                    - wordpress
        environment:
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=hstackcms2018.com
            - WORDPRESS_DB_NAME=db_hstackcms
            - WORDPRESS_TABLE_PREFIX=wp_
        volumes:
            - ./volumedata/www:/var/www/html:rw
            - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    mysql:
        image: mysql_v1
        build:
            context: .
            dockerfile: Dockerfile.mysql
        hostname: mysql
        privileged: true
        restart: always
        ports:
            - 3306:3306/tcp
        networks:
            wordpress:
                aliases:
                    - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=hstackcms2018.com
        volumes:
            - ./volumedata/mysql:/var/lib/mysql
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    redis:
        image: redis:4.0.6
        hostname: redis
        privileged: true
        restart: always
        networks:
            wordpress:
                aliases:
                    - redis
        volumes:
            - ./volumedata/redis:/data:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
networks:
    wordpress:
#        external: true
